# Generated by Django 4.0.3 on 2022-04-11 03:57

from django.db import migrations, models
import mysite.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_alter_recipe_mod_date_alter_recipe_pub_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeimage',
            name='image',
            field=models.FileField(storage=mysite.storage_backends.MediaStorage, upload_to=''),
        ),
    ]
