# Generated by Django 4.0.3 on 2022-04-11 04:13

from django.db import migrations, models
import mysite.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_alter_recipeimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeimage',
            name='image',
            field=models.ImageField(storage=mysite.storage_backends.MediaStorage, upload_to=''),
        ),
    ]
