# Generated by Django 4.0.3 on 2022-04-11 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_alter_recipe_mod_date_alter_recipe_pub_date'),
        ('recipes', '0012_alter_recipeimage_image'),
    ]

    operations = [
    ]
