# Generated by Django 4.0.3 on 2022-04-18 02:18

from django.db import migrations, models
import django.db.models.deletion
import mysite.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_merge_20220411_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.recipe'),
        ),
        migrations.AlterField(
            model_name='recipeimage',
            name='image',
            field=models.ImageField(blank=True, storage=mysite.storage_backends.MediaStorage, upload_to=''),
        ),
    ]
